#ifndef ENUMS_HPP
#define ENUMS_HPP

enum MajorState
{
    INIT_SEARCH,
    SEARCH_FIRE,
    SEARCH,
    DELIVER,
    RETURN_HOME
};

enum MinorState
{
    RUN,
    FOUND_FIRE,
    FOUND_SURVIVOR,
    FOUND_GROUP,
    FOUND_FOOD,
    VERIFY_FIRE,
    COMPLETE
};

/*
enum MachineStates{
    STARTINGCOURSE = 0,
    DRIVETOCORNER = 1,
    RUNINITIALSEARCH = 2,
    LOOKFORFIRE = 5,
    SCANNINGFIRE1 = 6,
    SCANNINGFIRE2 = 7,
    STOPPED = 8,
    COUNT = 9// ALWAYS MAKE COUNT LAST, UGLY SOLUTION TO DETERMINE ITEMS IN ENUM
};


enum SearchingStates{
    DRIVETOPOINT = 0,
    GRIDSEARCH = 1
    //COUNT // ALWAYS MAKE COUNT LAST, UGLY SOLUTION TO DETERMINE ITEMS IN ENUM
};
*/

#endif
